[package]
name = "cpu-benchmark"
version = "0.1.0"
edition = "2021"
description = "Tool for CPU benchmarking"
categories = ["command-line-utilities"]

[dependencies]
sysinfo = "0.33.0"
indicatif = "0.17.9"
systemstat = "0.2.3"


[profile.release]
lto = "fat"
strip = "debuginfo"